import type { OutputVariable } from "./types.js";

export const DASHBOARD_VARIABLES: OutputVariable[] = [
  {
    name: "Population",
    sector: "population",
    juliaPrefix: "pop",
    juliaVar: "POP",
    description: "Total world population",
    unit: "Mp (millions of people)",
    minRange: 0,
    maxRange: 12000,
  },
  {
    name: "GDP per Person",
    sector: "population",
    juliaPrefix: "pop",
    juliaVar: "GDPP",
    description: "Global GDP per person",
    unit: "k$/person/year",
    minRange: 0,
    maxRange: 80,
  },
  {
    name: "Observed Warming",
    sector: "climate",
    juliaPrefix: "cli",
    juliaVar: "OW",
    description: "Global mean temperature rise above pre-industrial",
    unit: "°C",
    minRange: 0,
    maxRange: 5,
  },
  {
    name: "Inequality Index",
    sector: "demand",
    juliaPrefix: "dem",
    juliaVar: "INEQ",
    description: "Ratio of owner income to worker income",
    unit: "ratio",
    minRange: 0,
    maxRange: 2,
  },
  {
    name: "Average Wellbeing Index",
    sector: "wellbeing",
    juliaPrefix: "wel",
    juliaVar: "AWBI",
    description: "Composite wellbeing index combining material and social factors",
    unit: "index",
    minRange: 0,
    maxRange: 2.5,
  },
  {
    name: "Social Tension",
    sector: "wellbeing",
    juliaPrefix: "wel",
    juliaVar: "STE",
    description: "Social tension index driven by inequality and unmet expectations",
    unit: "index",
    minRange: 0,
    maxRange: 2,
  },
];

export const EXTENDED_VARIABLES: OutputVariable[] = [
  ...DASHBOARD_VARIABLES,
  {
    name: "GDP",
    sector: "inventory",
    juliaPrefix: "inv",
    juliaVar: "GDP",
    description: "Total global GDP",
    unit: "G$/year",
    minRange: 0,
    maxRange: 600000,
  },
  {
    name: "CO2 Emissions",
    sector: "energy",
    juliaPrefix: "ene",
    juliaVar: "CO2EMPP",
    description: "CO2 emissions from energy production",
    unit: "GtCO2/year",
    minRange: 0,
    maxRange: 60,
  },
  {
    name: "Renewable Electricity Fraction",
    sector: "energy",
    juliaPrefix: "ene",
    juliaVar: "FREF",
    description: "Fraction of electricity from renewable sources",
    unit: "fraction",
    minRange: 0,
    maxRange: 1,
  },
  {
    name: "Life Expectancy",
    sector: "population",
    juliaPrefix: "pop",
    juliaVar: "LE",
    description: "Global average life expectancy",
    unit: "years",
    minRange: 40,
    maxRange: 90,
  },
  {
    name: "Unemployment Rate",
    sector: "labourmarket",
    juliaPrefix: "lab",
    juliaVar: "UR",
    description: "Global unemployment rate",
    unit: "fraction",
    minRange: 0,
    maxRange: 0.3,
  },
  {
    name: "Food Cost Index",
    sector: "foodland",
    juliaPrefix: "foo",
    juliaVar: "FCI",
    description: "Relative food cost index",
    unit: "index (1980=1)",
    minRange: 0,
    maxRange: 3,
  },
  {
    name: "Social Trust",
    sector: "wellbeing",
    juliaPrefix: "wel",
    juliaVar: "STR",
    description: "Social trust index",
    unit: "index",
    minRange: 0,
    maxRange: 1.5,
  },
  {
    name: "CO2 Concentration",
    sector: "climate",
    juliaPrefix: "cli",
    juliaVar: "CO2C",
    description: "Atmospheric CO2 concentration",
    unit: "ppm",
    minRange: 280,
    maxRange: 800,
  },
];
